### ISSUE TITLE
Font rendering in status_bar, dmenu and st

### ISSUE THREAD

**Issue by ghost** [michaelforney/velox#27]
Hi. I'm having problems with font rendering in status_bar and ported dmenu and st. It seems like like antialiasing is disabled. I was playing with different fonts, dpi, and different configs in /etc/fonts and font rendering *was* affected by those changes, except antialiasing. Do these program override antialiasing somehow? Or is it some error with my configuration. I don't mind implementing anything myself just point me in the right direction please.

**Comment by michaelforney** [comment]
Yeah, text is rendered in monochrome:
https://github.com/michaelforney/wld/blob/master/font.c#L180

Anti-aliasing requires being able to do alpha blending, and currently the intel backend of wld can't do this (since it is not supported by the BLT engine and requires more complex 3D operations).

I think though that I will change these client programs to just use software rendering via pixman, since it is really just the compositor that wants hardware-accelerated copies and fills.

**Comment by ametisf** [comment]
I've found [related issue](https://github.com/michaelforney/wld/issues/3) in wld. I really like the idea of using Vulkan, so I may try to learn something and hopefully make it work some day.

**Comment by DmitryHetman** [comment]
How to launch Velox?

**Comment by DmitryHetman** [comment]
All libraries should use Vulkan.

**Comment by DmitryHetman** [comment]
Use bitmap font for status bar and terminal.
