### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by woegjiub** [michaelforney/velox#7]
`make: *** No rule to make target '/usr/local/share/swc/swc.xml', needed by 'protocol/swc-client-protocol.h'.  Stop.`

This is with the latest versions of swc, dmenu-wl and wld from git.

Are there any missing dependencies in https://aur.archlinux.org/packages/velox-wl-git/?

**Comment by michaelforney** [comment]
It looks like the swc pkgbuild is wrong. It runs make using the default prefix (/usr/local), which generates the swc.pc file, then installs with PREFIX=/usr.

It should set the same prefix for both make invocations, or just construct a config.mk file before building which sets the right prefix.

This bug was probably exposed by d187c98c157ee13baa8258d50da1952e69b348ba, which sets the default prefix back to /usr/local.

**Comment by woegjiub** [comment]
Thankyou for looking into that, I'll let the package maintainer know.
